ktlint style added
benjaglobant/HarryPotterApp pull request #2
Opened 2020-06-25 19:45 UTC by benjaglobant

In this PR I have just added the ktlint codestyle to the project.
 -ktlint added in "app" module.
 -ktlint added in "data" module.
 -ktlint added in "di" module.
 -ktlint added in "domain" module.

2020-06-25 19:48 UTC, SartiMau approved these changes

2020-06-25 20:10 UTC, nicolbidone approved these changes

2020-06-26 12:55 UTC, lucianoeli approved these changes

2020-06-26 13:00 UTC, hernanhorquin96 approved these changes

2020-06-26 13:08 UTC, mauroLonghi requested changes
Update Ktlint dependency

2020-06-26 13:31 UTC, SartiMau approved these changes

2020-06-26 13:34 UTC, mauroLonghi approved these changes

2020-06-26 13:35 UTC, hernanhorquin96 approved these changes

2020-06-26 15:56 UTC, nicolbidone approved these changes

2020-06-26 15:56 UTC, merged